<vue-state-wrapper :assessment="{{$assessment ?? json_encode(null)}}"
                   :assessment-courses="{{$assessmentCourses ?? json_encode(null)}}"
                   :completions="{{$planning->student->completions}}"
                   :planning-id="{{$planning->id}}"
                   :planning="{{$planning}}"
                   :semesters="{{ $semesters }}"
                   :specialization-year="{{ $specializationYear ?? json_encode(null)}}"
                   :specialization="{{ $specialization ?? json_encode(null)}}"
                   :specialization-courses="{{$specializationCourses ?? json_encode(null)}}"
                   :cross-qualification-year="{{ $crossQualificationYear ?? json_encode(null)}}"
                   :cross-qualification="{{ $crossQualification ?? json_encode(null)}}"
                   :cross-qualification-courses="{{$crossQualificationCourses ?? json_encode(null)}}"
></vue-state-wrapper>
